### ISSUE TITLE
Hard readability of coordinates label

### ISSUE THREAD

**Issue by michaelwille** [ericmandel/js9#11]
Hi Eric,

I have noticed another issue, this time concerning the color of the coordinates and value label in the upper left of the canvas. When the displayed image is small enough, the label is displayed in black letters (which is nice on the light grey canvas background). At some point, the label color is switched to green when the image zoom level is increased. Unfortunately, this seems to happen too early, which results in a pretty hard to read green on grey (see attached image).

Also, there are other scenarios (e.g. image height > width) where the image does not use the full width of the canvas. In these cases, the green label is also (at least partly) written on the grey canvas.

Maybe it would make sense to put the label into a small box with a uniform color? It might not look as nice but it would guarantee readability independent from the local background color/pattern. Alternatively, the label could maybe be moved to the associated menu bar. What do you think?

![js9_green_label](https://cloud.githubusercontent.com/assets/8819648/11371593/93927404-92c9-11e5-9412-05785583cc6a.jpg)

**Comment by ericmandel** [comment]
The color choice code was left-over from early prototyping days. I've improved it with a more precise calculation of the height of the message area. Give it a try and see if it's any better for you. That said, you have other options:

1. have you tried the infoBox plugin? Its much nicer but of course uses up some real estate
2. you can change the colors of the text using the JS9.textColorOpts preferences.
3. you can suppress the on-image valpos display entirely by setting:
````
JS9.globalOpts.internalValPos = false
````
and write a plugin that tracks mousemove events and calls JS9.GetValPos(). 
See [http://js9.si.edu/js9/js9plugins.html](http://js9.si.edu/js9/js9plugins.html).

Or we continue the conversation ...

**Comment by michaelwille** [comment]
Thank you for the correction and the nice suggestions! They sound promising and I will give them a try the next few days. I am pretty sure that I will be able to work out a good solution this way and I was not aware of the possibility to change the color of the label so easily.
