### ISSUE TITLE
loading files served from a separate site

### ISSUE THREAD

**Issue by havok2063** [ericmandel/js9#15]
My data files are served on a separate web server than my site is run from.  I normally access them through a separate URL.  Is it possible to have JS9.Preload() or .Load() accept an absolute URL path to a data file, rather than a relative filesystem link?

**Comment by ericmandel** [comment]
Yes and no, mainly no. The Web's **same-origin policy** mandates that the image data must be located on the same server as the javascript used to access it. The alternatives are:

1. if the **data server is CORS-enabled**, it can tell the browser that its OK to allow javascript from another host to access the image data. I've never done this, but its pretty standard (Dropbox supports it, for example).

2. your JS9 application server can **proxy the data files**. Basically, you set up the JS9 back-end server to make a request of the data server. The data is retrieved onto the JS9 server, stored in a temp directory, and then served from there, so same-origin does not come into play.

CORS is standard but it depends on how much control you have over the data server configuration.

**Comment by ericmandel** [comment]
By the way, some astronomical archives (such as SDSS) are CORS-enabled, in which case JS9.Load() will work with an absolute URL.

**Comment by ericmandel** [comment]
@havok2063 Have you made any progress with this issue? Or should we close it?

**Comment by havok2063** [comment]
@ericmandel I have not had a chance to work on this at all.  This may not end up being as big an issue as I thought it would.  I think we can close this for now, and if it turns out it's a problem then we can reopen it.

**Comment by ericmandel** [comment]
@havok2063 OK, let me know if I can help with anything.
