### ISSUE TITLE
mathematical operations between extensions

### ISSUE THREAD

**Issue by havok2063** [ericmandel/js9#16]
New issue from previous thread. "I've always wanted the ability to do this in DS9 and was disappointed it was never there. Image extension arithmetic. I'd like the ability to do mathematical operations (add, subtract, etc) on different extensions, and make a new image. Or take the mean of some part of one extension and add it to another. Stuff like that. Do you think something like that is possible?"

**Comment by ericmandel** [comment]
I'm traveling right now, butl realized that this is easy (except for the graphical user interface). All we need do is take an existing cfitsio program that does FITS image arithmetic, compile to JavaScript and run it in the JS9 Emscripten environment. FITS output becomes either a new raw layer or new file. The UI Is tough but let's think about that once we get the extension stuff finished. Also need to find a good C program... I know some possibilities but am open to suggestions...

**Comment by ericmandel** [comment]
@havok2063 I have implemented basic image arithmetic between two images or between an image and a constant. There is a JS9.ImarithData() public access routine underlying the View->imarith plugin. If you load your FITS extensions into "separate files" using the multi-extension plugin, you should be able to combine them in various ways using the imarith plugin. Let me know what you find ...

**Comment by ericmandel** [comment]
@havok2063 this imarith support is now in use by our science ed department, so I'll close the issue. Feel free to re-open if necessary.
