### ISSUE TITLE
TypeError: Argument 1 of CanvasRenderingContext2D.createImageData is not a finite floating-point value.

### ISSUE THREAD

**Issue by briehanlombaard** [ericmandel/js9#18]
Hi Eric,

I've upgraded from v1.5 to v1.8 and get this error when using either `JS9.Preload` or `JS9.Load` to load an initial image into JS9. This only happens when loading a PNG.

The error is in the `createImageData` call below:

```
    // create an RGB image if necessary
    if( !rgb.img                         ||    
        (rgb.img.width  !== sect.width)  ||
        (rgb.img.height !== sect.height) ){
        rgb.img = ctx.createImageData(sect.width, sect.height);
    }
```

And the `sect` object looks like this:

`Object { zoom: 1, ozoom: 1, xcen: NaN, ycen: NaN, width: NaN, height: NaN, x0: NaN, y0: NaN, x1: NaN, y1: NaN }`

Any idea if I'm doing something wrong here?

**Comment by ericmandel** [comment]
Hi Briehan,

I can't reproduce this yet. The preload demo seems to work: http://js9.si.edu/js9/js9preload.html

Is there any chance that you are picking up the old js9support.js file with the new js9.js file? We know that Chrome is pretty aggressive about caching files.

Also, are you talking about a PNG file that is converted from FITS using fits2png/tpos or an "ordinary" PNG file?

**Comment by ericmandel** [comment]
@briehanlombaard Any new word on this? I'd like to get you all fixed up as soon as possible.

**Comment by briehanlombaard** [comment]
Hi Eric,

Sorry for being so slow to get back to you. I'm using an [ordinary PNG](https://bytebucket.org/saao/shoc-web/raw/74c67dc0f31be9bc79f728790d16d4ce7068eac0/app/static/img/blank.png).

**Comment by ericmandel** [comment]
Hmmm ... I wasn't aware that you ever could load an ordinary PNG file (I thought it was only drag and drop) ... and I don't seem to be able to do it on v1.5. Are you using fitsy.js or the internal cfitsio?

**Comment by briehanlombaard** [comment]
It looks like we stopped using fitsy.js when we upgraded to v1.5

**Comment by briehanlombaard** [comment]
I should add: let me know if what I'm doing is not supported. It should be easy enough to load in a blank FITS file if that's the way it's supposed be done.

**Comment by ericmandel** [comment]
It's good that you moved away from fitsy.js, as new capabilities (e.g. multi-extension FITS support) can't be done using that simple code. But let me look into support for jpeg files. If it worked with v1.5, it ought to work now. I do apologize if bugs have been introduced. Usually that indicates that the software is getting old, but in this case it might just mean that I'm getting old.

**Comment by ericmandel** [comment]
@briehanlombaard Hi Briehan, oops it looks like I deleted one too many lines from JS9.Image.prototype.mkRawDataFromPNG. I committed the fix to GitHub, but you can just add the line listed below for testing. It should work, in which case you can close this issue ...
````
@@ -962,6 +962,7 @@ JS9.Image.prototype.mkRawDataFromPNG = function(){
     // see if we have a real PNG file instead of a representation file
     if( (i < 15) || realpng ){
        // holy moly, its a real png file!
+       this.mkRawDataFromIMG(this.offscreen.img);
        // save the off-screen image and return;
        return;
     }
````

**Comment by briehanlombaard** [comment]
Thanks Eric. That fixed it.
