### ISSUE TITLE
Open alternative WCS 

### ISSUE THREAD

**Issue by jzuhone** [ericmandel/js9#20]
The desktop version of DS9 supports multiple WCS in the same file, e.g. WCS a - z. It would be good to have this support in JS9 as well.

**Comment by ericmandel** [comment]
@jzuhone Do you have an example FITS file? JS9 just uses the standard wcsinit() on a FITS header, so presumably I can add this if I can recognize the existence of alternate WCS ...

**Comment by jzuhone** [comment]
The file here has several image HDUs, each of which have a default linear WCS and a WCSa that is celestial: https://girder.hub.yt/api/v1/item/57506e8d611437000153b168/download

**Comment by ericmandel** [comment]
@jzuhone Oh, I see the alternate syntax, which looks like a hack! Let me get into it, I don't see explicit support in Jessica Mink's WCS library, but it also looks like you just have to separate out the alternate WCS keywords and call wcsinit() on them.

**Comment by jzuhone** [comment]
I think it's non-standard, but it's standard "enough" that DS9 already recognizes it?

**Comment by ericmandel** [comment]
Oh, interesting, looks like its part of the official WCS canon:

http://www.atnf.csiro.au/people/mcalabre/WCS/wcs.pdf

I'll look into it in the next couple of weeks.

**Comment by jzuhone** [comment]
Cool, thanks!

**Comment by ericmandel** [comment]
@jzuhone I added support for alternate WCS on two levels: the WCS->alternate wcs menu option allows you to choose an alternate WCS, if present. And the JS9.SetWCS() public routine lets you set the alternate WCS programmatically (documentation in the publicapi.html page). It's all uploaded in GitHub and also installed on the http://js9.si.edu web site.

Feel free to complain ... or close this issue if you are satisfied.
