### ISSUE TITLE
Package JS9 for NPM

### ISSUE THREAD

**Issue by astrofrog** [ericmandel/js9#21]
It would be great if JS9 could be packaged for NPM (https://www.npmjs.com/)

The background for this is that @gogrean and I are developing a plugin for Jupyter lab that uses JS9 and it would be much simpler to distribute this to people if JS9 was included on NPM.

**Comment by ericmandel** [comment]
@astrofrog This is a good idea.  Unless you have an immediate need, I'll plan to publish an npm package with the release of js9 1.10 (probably first half of August). I started to play with publishing a package today, but got messed up and decided I'd better look at the documentation ...

Are you aware that  the js9-allinone.js and js9-allinone.css files are available on the js9 web site:

http://js9.si.edu/jupyter/js9-allinone.js
http://js9.si.edu/jupyter/js9-allinone.css

You can read about them in:

http://js9.si.edu/js9/help/python.html

They might be of some use, depending on what you app does (e.g. they will not support back-end analysis).

Let me know your time-scale.

**Comment by astrofrog** [comment]
> I'll plan to publish an npm package with the release of js9 1.10 (probably first half of August)

This would be great - thanks! (first half of August would be early enough for us)

**Comment by astrofrog** [comment]
Just to clarify, using the ``js9-allinone.js`` and ``js9-allinone.css`` would not be sufficient in our case, because the Jupyter developers want to avoid bundling any JS code directly, and instead want to manage dependencies via NPM.

**Comment by ericmandel** [comment]
OK, thanks, I have no real experience with Jupyter and certainly no experience with their development protocols. I'm sure you have seen #10, which also deals with Jupyter-related development ... but I can only respond to specific requests from you experts ...

**Comment by ericmandel** [comment]
@astrofrog @gogrean I published a snapshot of js9 (called 1.9.1) on npm. I'll keep it up to date when I make "official releases", but this version of js9 should work fine:
````
npm install js9
````
It installs under a node_modules directory, which is not surprising, but a bit odd for ordinary use ...

Let me know if this is what you wanted, and if so, feel free to close this issue.

**Comment by ericmandel** [comment]
@astrofrog @gogrean The only issue I can see is that the 'npm install' has ignored js9's node_modules directory. (js9 has the option of running a node-based back-end server, but this is not necessary to use js9.) I suspect this is not a problem for your application, but it is an artifact of using npm to manage a non-node package. Let me know if it is a problem for you and we'll work something out.

**Comment by mgckind** [comment]
@astrofrog If this is of any help just let us know, we are facing similar issues for the Jupyter Js9 integration. We are trying both server and client side integration. baby steps still :) https://github.com/mgckind/jjs9

**Comment by ericmandel** [comment]
@astrofrog @gogrean I fixed the above-mentioned problem with the missing node_modules directory ... installing via npm (v1.9.4) should now give you a complete js9 package.
