### ISSUE TITLE
Passing a base64 encoded FITS file requires filename to be explicitly passed

### ISSUE THREAD

**Issue by astrofrog** [ericmandel/js9#22]
The following call does not work (base64 code shortened for readability):

```javascript
JS9.Load("U0lNUExFICA9ICAgICA...");
```

but everything works fine if I explicitly pass a filename in the options:

```javascript
JS9.Load("U0lNUExFICA9ICAgICA...", {"filename":"test.fits"});
```

However, this is not mentioned in the documentation. Would it be possible to either fix this so that the filename is not required, or update the documentation to mention this requirement?

(cc @gogrean)

**Comment by ericmandel** [comment]
@astrofrog @gogrean I've never tried this, but if it does not work, it's a bug, and I'll fix it in the next few days. Can I assume your encoded file is a FITS file, or are you loading an PNG/JPEG/etc image?

**Comment by astrofrog** [comment]
@ericmandel - this is indeed an encoded FITS file. Let me know if you need a full example to reproduce this.

**Comment by ericmandel** [comment]
@astrofrog A full example would be helpful, saving me the trouble of figuring out how to generate the first one (I imagine I'll have to test a bunch of them before calling it fixed).

**Comment by astrofrog** [comment]
@ericmandel - here goes: https://gist.github.com/astrofrog/1e287c3cc787818bdf5d784460269c52

If you remove the ``{"filename":"test.fits"}`` you will see an error

**Comment by ericmandel** [comment]
@astrofrog Duh ... in the case where no filename was passed, I was "cleverly" making up a filename with non-alphanumeric characters in it, and the emscripten virtua file system did not like that. So now the anonymous name is ... "Anonymous" (though you can change the ANON variable to anything you like in js9Prefs.json) and everything works better. It's updated in GitHub, so if this works for you, feel free to close this issue.

**Comment by astrofrog** [comment]
Thanks for the quick fix!! We'll test this out shortly.

**Comment by ericmandel** [comment]
@astrofrog Hmmm ... I just uploaded another change to ensure uniqueness of the anonymous filenames in cases where you load more than one of them at a time.
