### ISSUE TITLE
Zscale public API setting

### ISSUE THREAD

**Issue by samverstocken** [ericmandel/js9#27]
Is there a function to enable one of the zscale options (z1/z2 or (z1/data max) from the public API?

**Comment by ericmandel** [comment]
Hmmm … this should be supported in JS9.SetScale() but it looks like I just forgot. I'll add it in the next few days, but as a work-around, you can do this:
````
im = JS9.GetImage({display: "foo"})

im.params.scaleclipping = "zmax"; 
im.params.scalemin = im.params.z1;
im.params.scalemax = im.raw.dmax;

im.params.scaleclipping = "zscale";
im.params.scalemin = im.params.z1;
im.params.scalemax = im.params.z2;
````

**Comment by ericmandel** [comment]
Never mind the above work-around, I added "zmax" and "zscale" to JS9.SetScale:
````
JS9.SetScale("zscale")
JS9.SetScale("zmax")
JS9.SetScale("dataminmax")
````
It's been uploaded into GitHub, so let me know if you have problems.

**Comment by samverstocken** [comment]
Thanks, that seems to work!
