### ISSUE TITLE
What PNG library is needed for fits2png support?

### ISSUE THREAD

**Issue by DougBurke** [ericmandel/js9#29]
I just tried building within a docker container, so it doesn't have many packages installed, and saw this from the `configure` step:

```
checking for png library (for building fits2png)... fits2png will not be built
```

What library (or libraries) does it need here? Did I miss it in the documentation?

**Comment by ericmandel** [comment]
@DougBurke You don't need to build fits2png, its deprecated. I'll add a note to that configure output line to make that fact more clear.

**Comment by DougBurke** [comment]
Ta. Doug

**Comment by ericmandel** [comment]
All set and updated in GitHub.

**Comment by DougBurke** [comment]
My build now says the following which does tell me not to bother about this, but the `good` is a bit surprising ;-)

```
checking for png library (for building deprecated fits2png)... good ... fits2png will not be built
```

**Comment by ericmandel** [comment]
OK ... I remove the word "good", I guess it didn't re-assure you quite as I thought it would!
