### ISSUE TITLE
What's the best approach to js9 in a Jupyter notebook?

### ISSUE THREAD

**Issue by DougBurke** [ericmandel/js9#30]
@ericmandel is https://github.com/gijzelaerr/js9notebook the best way to get js9 in a Jupyter notebook, or does pyjs9 replace it? Ta.

**Comment by ericmandel** [comment]
I'm not sure about the state the effort you mention ...  the most active Jupyter project I know about (based on back and forth communication) was done by @mgckind for DES:

https://github.com/mgckind/jjs9

so perhaps that would be a good starting point.

I have not spent much time with Jupyter this past year, but using the allinone files should still work:
````
%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="https://js9.si.edu/js9/js9-allinone.css">
<script type="text/javascript" src="https://js9.si.edu/js9/js9-allinone.js"></script>
````
and if there is a problem, obviously I'll fix it.

**Comment by ericmandel** [comment]
No, that's a very important file! What technique are you using? allinone? I would have thought the allinone technique would find that file properly  ... though, as I said, I haven't tried Jupyter in a long while.

**Comment by ericmandel** [comment]
Oh .... I tried my old Jupyter setup and got the same error. Let me look into it ...

**Comment by mgckind** [comment]
Hi @DougBurke and @ericmandel , yes I wrote that wrapper some time ago, but recent developments from Jupyter an Jupyter lab aren't compatible anymore (plus some extra features in js9). I tried a couple of months ago again but didn't spend too much time with it. We do want to revisit this issue next January/February.

**Comment by ericmandel** [comment]
OK, so for now, I should get the basic technique (see above) working. @DougBurke the problem you report is that your browser is trying to load the WebAssembly version and I bet that does not yet work in Jupyter. So I need to ensure that the non-wasm code is loaded. I'll work on that a bit and get back to you.

**Comment by ericmandel** [comment]
@DougBurke and @mgckind  I fixed the Jupyter problem (sigh ... once again, Jupyter HTML syntax was not behaving in a standard browser-like way). You should now be able to use the simple-minded construct:
````
%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="https://js9.si.edu/js9/js9-allinone.css">
<script type="text/javascript" src="https://js9.si.edu/js9/js9-allinone.js"></script>
````
Since Jupyter does not quite behave in a standard fashion, there may be some problems with specific functions, which have to be investigated on a case-by-case basis. Let me know when you find something ...

Obviously, I can use all the help I can get regarding Jupyter support.

**Comment by DougBurke** [comment]
Thanks. I've run out of free time for this project at the moment (what with
the start of the work week). I'll let you know when I get time to try your
new code out.

**Comment by DougBurke** [comment]
@ericmandel I did have time to re-try this morning, and I no-longer see the error message pop up.

**Comment by ericmandel** [comment]
And, better yet, you should be able to drag and drop an image onto the display ...

**Comment by o-smirnov** [comment]
> You should now be able to use the simple-minded construct:

This currently doesn't work for me.  The cell produces no output. The JS console shows:

```
...
.(anonymous function) @ js9-allinone.js?_=1530609214228:281
(anonymous) @ js9-allinone.js?_=1530609214228:658
(anonymous) @ js9-allinone.js?_=1530609214228:680
js9-allinone.js?_=1530609214228:3059 Uncaught TypeError: Cannot read property 'mouse' of undefined
    at js9-allinone.js?_=1530609214228:3059
    at js9-allinone.js?_=1530609214228:3218
```

But maybe that's an issue on your end, because it works if I change the URLs to point to my local installation, i.e.:

```
  <link type="text/css" rel="stylesheet" href="/files/.radiopadre/js9-www/js9-allinone.css">
  <script type="text/javascript" src="/files/.radiopadre/js9-www/js9-allione.js"></script>
```

And I can drag-and-drop and work with local FITS files. Two issues though: 

* trying to load a server-side file with ``JS9.Load("/files/path.fits")`` fails with a pop-up saying ``JS9 ERROR: no FITS module available to process FITS file``

* JS9 menus appear stuck to the top left of my browser window, rather than in the expected location --
 see screenshot:

![image](https://user-images.githubusercontent.com/6470079/42213223-74fac55e-7eb8-11e8-8660-98e3c36dbcde.png)

CC  @gijzelaerr @Mulan-94

**Comment by ericmandel** [comment]
> This currently doesn't work for me. The cell produces no output. The JS console shows:

@o-smirnov Sigh ... the main web site seems to work for me, see below. I'll (try to) update my  reltively old Jupyter in miniconda. Perhaps this is the problem to which @mgckind was referring when he said that JS9 broke with the updated Jupyter.

<img width="827" alt="screen shot 2018-07-03 at 8 54 20 am" src="https://user-images.githubusercontent.com/3028875/42221076-d960da20-7e9e-11e8-8224-912a7e39e4fc.png">

> JS9 menus appear stuck to the top left of my browser window, rather than in the expected location

This could be the start of a religious war: our Mac-based users here insist on left-justified menus ... when I get some time, I'll try to parameterize it!

**Comment by o-smirnov** [comment]
> But maybe that's an issue on your end, because it works if I change the URLs to point to my local installation, i.e.:

Sorry, scratch that. The ``js9-allinone.js`` invocation **does not** work on my local installation either (turns out I had another Jupyter cell that **did** have the necessary tags in it, and this is what made things work...) What does work for me is the following cell:

```
%%html
  <div class="JS9Menubar"></div>
  <div class="JS9"></div>
  <script type="text/javascript" src="/files/js9-www/js9prefs.js"></script>
  <script type="text/javascript" src="/files/js9-www/js9support.min.js"></script>
  <script type="text/javascript" src="/files/js9-www/js9.min.js"></script>
  <script type="text/javascript" src="/files/js9-www/js9plugins.js"></script>
  <link type="text/css" rel="stylesheet" href="/files/js9-www/js9-allinone.css">
```

...in that a display at least is created. This is orthogonal (I think) to the helper issues we've been discussing in https://github.com/gijzelaerr/js9notebook/issues/2.

**Comment by o-smirnov** [comment]
@ericmandel, just a thumbs-up from our little pipeline workshop in the middle of nowhere:

![screenshot from 2019-02-21 19-26-24](https://user-images.githubusercontent.com/6470079/53189315-e40d5880-360f-11e9-953b-9c760798c23b.png)

People are extremely happy with JS9 functionality. Right @bennahugo?

**Comment by ericmandel** [comment]
Beautiful! And very gratifying! We did some really good work together last spring ... 

Not the middle of nowhere in my book, not in terms of the evolution of astrophysics software ...

**Comment by ericmandel** [comment]
p.s. @o-smirnov what's that intriguing button on the RHS of the menubar?

**Comment by o-smirnov** [comment]
Ah that resets the colormap and scale to min/max. I find myself needing that function so frequently, I just added the button in the partner display code. I also needed to add a checkbox to lock the colormap/scale across images.

If you can add these features to the core functionality some day, that'd be great.

**Comment by ericmandel** [comment]
Can you please post or point to the code you added (to make sure I understand) and I’ll try to do something next week when I return from the road ...

**Comment by wkerzendorf** [comment]
Just wanted to give a 👍 to making this a jupyter notebook widget.

**Comment by mgckind** [comment]
We have done some work in this space @wkerzendorf maybe is useful https://github.com/mgckind/jjs9

**Comment by ericmandel** [comment]
Most of the thanks in this arena should go to @mgckind and @o-smirnov (and their respective collaborators) for work on their two Jupyter-based analysis systems.

In my ignorance, I believe we still are missing a simple and general-purpose way of importing JS9 into a notebook, beyond use of the %html directive. I'm ready to help on the JS9 end, if someone wants to take that on ...
