### ISSUE TITLE
problem using CGI helper on non-privileged port

### ISSUE THREAD

**Issue by kglotfelty** [ericmandel/js9#31]
I ran in a snag when I was trying to setup a local, server-side analysis site.  For testing, I'm using the python built-in  web server (CGI enabled) 

```bash
python -m CGIHTTPServer
```

the problem is that it runs on the non-privileged port 8000 (variable).  This causes problems because the URL that js9 creates for the `helperCGI` doesn't include the port number

https://github.com/ericmandel/js9/blob/4da1d70af0ea4bc3d2eec6a4e6950431e4d1c426/js9.js#L7618

since there isn't a web-server running on :80 , the cgi kept failing.  I tried setting the `helperPort` but that didn't seem to do anything.

Looking at the code, it looks like there's support for a `globalOpts.helperURL` that I could use.(?)   But I'm curious if there's a reason not to use the `location.port` as part of the CGI URL?  

Kenny

**Comment by ericmandel** [comment]
@kglotfelty That's a bug, now fixed and updated in GitHub:

<img width="1272" alt="screen shot 2017-12-16 at 10 18 44 am" src="https://user-images.githubusercontent.com/3028875/34071859-45bbb97e-e24b-11e7-8e69-047c6383706c.png">

That said, I'm pretty sure you don't want to use CGI, even for testing. It doesn't support the pyjs9 scripting interface, for starters ...

**Comment by kglotfelty** [comment]
Thanks for the quick fix.  Confirmed it works with my test setup.

**Comment by ericmandel** [comment]
OK, great, I'll close this and look forward to the next problem report ...
