### ISSUE TITLE
 cfitsio.js: bad first element number        

### ISSUE THREAD

**Issue by gijzelaerr** [ericmandel/js9#4]
Hi! Thanks for making js9! This is exactly the tool I was looking for.

I have a problem with a custom fits file. When I upload or drop this fits file:

http://rodrigues.meqtrees.net/media//1-_yayskwg/output/results-dirty.fits

here:

http://js9.si.edu/

I get:

 cfitsio.js: bad first element number

Let me know if I can do something to get more debugging info.

**Comment by ericmandel** [comment]
This looks like a bug in how I handle images with NAXIS > 2. Your file has NAXIS == 4, with the dims of the last two axes == 1 and I must not be setting those "extra" axes properly ... somewhere. It's also broken in regcnts. I'll try to fix it in the next day or two ...

**Comment by ericmandel** [comment]
OK, this bug is fixed and updated, in both github repositories (regcnts and js9) and at http://js9.si.edu/
Please try another drag and drop ....

**Comment by gijzelaerr** [comment]
yes it is fixed! Thanks!
