### ISSUE TITLE
request: support averaging in fits2fits, not just binning

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#40]
I've realized the "bin" option in fits2fits actually performs as advertised, i.e. sums the pixels in a bin. Would it be possible to add an option to take the mean value instead of a sum?

We usually deal with flux density images, so summing breaks our units...

**Comment by ericmandel** [comment]
Yes, I can do that (not in one day, though) ... must be nice to have so many photons that you need to take the mean (not the X-ray experience!)
