### ISSUE TITLE
would be nice to have a "hard fail" mode for the helper

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#41]
Given my rather fiddly attempts to get js9helper going in various scenarios, I'm frequently being tripped up by the "silent fail" behaviour of JS9 when it can't connect to the helper.

At present it quietly falls back to downloading full images via HTTP. So everything continues to work, albeit more slowly and with more browser memory use. I actually have to go to the JS console to figure out if the helper is being invoked or not. 

Could I ask for an option, e.g. ``globalOpts.requireHelper``? If False (which should be the default), keep current behaviour. If True, display an error dialog if it fails to connect to the helper. Then at least if I've broken something, I'll know immediately...

**Comment by ericmandel** [comment]
I assume you want an error in two cases:

1. if the helper does not connect
2. if the helper connects, but fits2fits find that the js9helper program is not available

Can you think of any other cases?

**Comment by ericmandel** [comment]
JS9.globalOpts.requireHelper support is updated in GitHub (default is false).

**Comment by o-smirnov** [comment]
Thanks, can confirm this option works.
