### ISSUE TITLE
need a "hard fail" mode for fits2fits

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#42]
Related to #41: I keep finding novel ways to make the fits2fits functionality silently fail and fall back to downloading full images. While I can see the value of this from a user's point of view, for a developer this behaviour can be very confusing, since it can only really be detected in the network console. Also, programmatically, if my code is e.g. trying to load a rebinned image of a certain size, it expects either a correctly sized image to come back, or a full failure -- it's very hard to deal with the "in between" situation when a full-resolution image arrives instead.

So I guess something similar to ``globalOpts.requireHelper`` would be nice. If true, and fits2fits fails for whatever reason, do not fall back to full images, but report an error instead.

Which raises another interesting issue -- are we going to need error codes from e.g. ``JS9.Load()`` at some point? At the moment I'm happy with a "hard fail" dialog, but at some point the partner displays code might grow sophisticated enough that I'll need to detect errors programmatically...

**Comment by ericmandel** [comment]
I've added a JS9.globalOpts.requireFits2Fits property which will throw an error on all of the fits2fits conditions (that I know about). You should continue to set JS9.globalOpts.requireHelper (which will fail if the helper is wanted but not available) and also use requireFits2Fits for the fits2fits failures. I hope that's all we need.

I'll look into JS9.Load ... I would have thought try{} catch{} would do it, but maybe not ...

**Comment by o-smirnov** [comment]
> I'll look into JS9.Load ... I would have thought try{} catch{} would do it, but maybe not ...

Ah of course, the error dialog only pops up because it's an uncaught exception, right? So indeed I can catch exceptions in the partners code, I don't need error codes...

**Comment by o-smirnov** [comment]
Thanks, the new property works.

**Comment by ericmandel** [comment]
> Ah of course, the error dialog only pops up because it's an uncaught exception, right? So indeed I can catch exceptions in the partners code, I don't need error codes...

No there is an explicit alert() called if JS9.globalOpts.alerts is turned on. So turning it off and doing a try{} should be just what you want ... but it doesn't work. So let me debug this.

**Comment by ericmandel** [comment]
> Which raises another interesting issue -- are we going to need error codes from e.g. JS9.Load() at some point? At the moment I'm happy with a "hard fail" dialog, but at some point the partner displays code might grow sophisticated enough that I'll need to detect errors programmatically...

As it turns out, async function are not caught in a try{} statement, so there is no way to catch an error on JS9.Load() as currently implemented. I think the new ES6 promises/async capabilities will deal with this,  but that the conversion is a big project.
