### ISSUE TITLE
JS9.Load() options to set the scale

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#43]
https://js9.si.edu/js9/help/publicapi.html#JS9.Load suggests I can set the scale type via the options argument to Load() -- are there similar options for the clipping min/max? Is there a full list of options somewhere?

**Comment by ericmandel** [comment]
You have to look at JS9.imageOpts in js9.js.

**Comment by ericmandel** [comment]
Hmmm ... you should be able to set scalemin and scalemax in the opts object instead of having to use onload. I'll add that, if possible ...

**Comment by ericmandel** [comment]
OK, you can now supply scalemin and scalemax to opts object during JS9.Load(). The only nuance is that you must also set scaleclipping to "user", or the values will be ignored (in favor of the default "dataminmax"), e.g.:
````
JS9.Preload("fits/snr.fits[events][pi==pha]",
                    {colormap: "heat", scale: "linear",
                     contrast: 5.625, bias: 0.1,
                     scaleclipping: "user", scalemin: 1, scalemax: 15,
	             onload: function(im){
		       JS9.SetZoom(2,{display: "myJS9"}); 
		       JS9.LoadSession("casa/casa.png.ses",
                                       {display:"myJS9"});}
                    }, 
````

**Comment by ericmandel** [comment]
I'll close this, but if something is not right, let me know ...
