### ISSUE TITLE
missing colorbar labels when clipping set to small values

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#44]
I've got a linear scale set, with clipping from -1e-5 to 1e-4 (fairly typical for our kinds of images). 

The colorbar labels go missing though:

![image](https://user-images.githubusercontent.com/6470079/44037671-293b6a4c-9f15-11e8-80d0-237870e67c9c.png)

(Things are going rather well, if I'm worrying about such trifles...)

**Comment by ericmandel** [comment]
Cool, thanks, I can fix that. I could use a test FITS file though, if one is conveniently available. Otherwise, most of the time is spent trying to reproduce the problem ...

**Comment by ericmandel** [comment]
Never mind, I took your last FITS file, divided each pixel value by 10000 and see the problem ...

**Comment by ericmandel** [comment]
This should be fixed now ...

<img width="529" alt="screen shot 2018-08-13 at 3 08 42 pm" src="https://user-images.githubusercontent.com/3028875/44052513-ce01d31e-9f0a-11e8-9dd8-fb49ed96de1a.png">

**Comment by o-smirnov** [comment]
Works now, thanks.
