### ISSUE TITLE
Adding too many colormaps breaks the Colors menu

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#46]
I've loaded up a whole slew of colormaps programmatically using JS9.AddColormap()... basically trying to have support for all the colormaps defined by matplotlib (which is a few dozen). This works just fine, but now the Colors menu has become unmanageably long. Is there a way to make the added colormaps appear in the "more colormaps..." submenu, instead of the main menu? Or else restrict which colormaps actually appear in the menu?

**Comment by o-smirnov** [comment]
OK, actually what you point out [here](https://github.com/ericmandel/js9/issues/45#issuecomment-414084123) is a solution I think...

**Comment by ericmandel** [comment]
I've added an optional opts to AddColormap, so that you can avoid adding to the top-level menu:
````
        JS9.AddColormap("cyan", [[0,0],[0,0]], [[0,0],[1,1]], [[0,0],[1,1]], {toplevel: false});
````
will do it. Just goes to show you ... I assumed that if you added a colormap, it would be important enough to add to the top!

**Comment by ericmandel** [comment]
I'll close this, but if something is not right, let me know ...
