### ISSUE TITLE
Can I disable zoom/pan on an image completely?

### ISSUE THREAD

**Issue by o-smirnov** [ericmandel/js9#47]
This would be very useful for the partners code preview image,

**Comment by ericmandel** [comment]
I'll implement some sort of disable capability for the same set of features/methods/capabilities we want to sync: "colormap", "pan", "scale", "wcssys", "wcsunits", "zoom".

But what is the the name of the routine? Disable? DisableMethod? DisableCapability?

**Comment by o-smirnov** [comment]
DisableControls and SyncControls perhaps?

**Comment by ericmandel** [comment]
Ummm ... it's funny: along with regions, these are the fundamental capabilities of all our astronomical image display programs stretching back to SAOimage in the 1980's. But what are they called as a class? I'll bet it never came up until today! Existential crisis coming? I'll try a thesaurus first.

**Comment by o-smirnov** [comment]
Render controls?

**Comment by ericmandel** [comment]
I'm thinking about a routine that allows one to configure core components:
````
core features: "colormap", "pan", "regions", "scale", "wcs", "zoom"

JS9.ConfigCore(feature|[features], whatToDo, whatOpts)

e.g:

JS9.ConfigCore(["colormap", "pan", "regions", "scale", "wcs", "zoom"],
			     "enable"/"disable");

JS9.ConfigCore(["colormap", "pan", "regions", "scale", "wcs", "zoom"],
			     "sync"/"unsync"
			     [sync_image_list]);
````
It will be important to support core configuration in the prefs file, but I think that just requires some processing of the prefs object.

**Comment by ericmandel** [comment]
Sigh, never mind, that syntax got too complicated. I added the ability to disable core functions more simply using JS9.SetParam (which presumably you will use to disable the preview image):
````
JS9.SetParam("disable", "scale");
JS9.SetParam("disable", ["zoom", "pan"])
JS9.SetParam("enable", "pan");
JS9.SetParam("enable", ["zoom", "scale"])
````
... of course you can disable functions at startup in your prefs file using imageOpts:
````
var JS9Prefs = {
  "globalOpts": {"helperType":	     "nodejs",
  ...
  "imageOpts":  {"colormap":	     "grey",
                 "disable":          ["zoom", "pan"],
  		 "scale":     	     "linear"}
}
````

**Comment by o-smirnov** [comment]
Perfect, that'll do nicely. Thanks!
