### ISSUE TITLE
Region positions with respect to Image

### ISSUE THREAD

**Issue by Stuermer** [ericmandel/js9#49]
When zooming into an image, using the mouse wheel, the region positions with respect to the pixels seem to change. I made a screencast showing the issue:

![screencast](https://user-images.githubusercontent.com/6728233/45769330-e9035180-bc04-11e8-8b9a-5111420b581f.gif)
Since it sometimes 'jumps' it almost looks like a rounding error to me.

**Comment by ericmandel** [comment]
Weird, I'll look into it ... probably not a two-minute fix!

**Comment by Stuermer** [comment]
Thank you very much for the quick fix.
I confirm both, the fix for the original issue and the crosshair artifact at certain zoom levels.

**Comment by ericmandel** [comment]
FYI, the crosshair artifact problem should be fixed in Github ...
