### ISSUE TITLE
JS9 ERROR: data missing from JS9 FITS object{}

### ISSUE THREAD

**Issue by briehanlombaard** [ericmandel/js9#5]
Hi Eric,

After upgrading from v1.1 to v1.5 I get this error during a "RefreshImage" call. I'm not sure why this is happening but I noticed when I comment out [this line](https://github.com/ericmandel/js9/blob/06e334ef5b37bdc92f968ea7c8a4f2641580ee95/js9.js#L10889) it still works and the error goes away.

**Comment by ericmandel** [comment]
Hi Briehan,

By inspection, I can see that the blob handler is wrong. The line you commented out should be (and now is) in an 'else' statement:

````
diff --git a/js9.js b/js9.js
index a1fc6f5..2349fbb 100644
--- a/js9.js
+++ b/js9.js
@@ -10885,8 +10885,9 @@ JS9.mkPublic("RefreshImage", function(fits, func){
            } else {
                JS9.error("no FITS module available to refresh this image");
            }
+       } else {
+           JS9.Image.prototype.refreshImage.apply(im, obj.argv);
        }
-       JS9.Image.prototype.refreshImage.apply(im, obj.argv);
     } else if( fits instanceof Blob ){
        JS9.Load.apply(null, arguments);
     }
````
The bug fix has been updated to GitHub but your hack will work for your purposes.

**Comment by briehanlombaard** [comment]
Thank Eric, that was quick :)
