### ISSUE TITLE
js9-allinone.js looks for port 2718

### ISSUE THREAD

**Issue by cylammarco** [ericmandel/js9#50]
The js9-allinone.js is trying to access port 2718 which is the default port for JS9Helper. An error message is outputted to the console:

> js9-allinone.js:21
>
> GET http://[host web address]:2718/socket.io/socket.io.js?_=1540554588423 net::ERR_CONNECTION_REFUSED
> 
> send @ js9-allinone.js:21
> ajax @ js9-allinone.js:21
> g @ js9-allinone.js:3498
> b.Helper.connect @ js9-allinone.js:3503
> b.Helper @ js9-allinone.js:3496
> b.init @ js9-allinone.js:3834
> (anonymous) @ js9-allinone.js:3894
> j @ js9-allinone.js:19
> k @ js9-allinone.js:19
> setTimeout (async)
> (anonymous) @ js9-allinone.js:19
> i @ js9-allinone.js:19
> fireWith @ js9-allinone.js:19
> fire @ js9-allinone.js:19
> i @ js9-allinone.js:19
> fireWith @ js9-allinone.js:19
> ready @ js9-allinone.js:19
> S @ js9-allinone.js:20`

Should the js9-allinone.js be completely stand-alone?

**Comment by ericmandel** [comment]
Yes, by default, js9-standalone.js should not be looking at a port. I'll fix that very soon.

As a work-around, if you load js9prefs.js, you should be able to set the helperType to "none":

````
"globalOpts": {"helperType":	     "none", ...}
````

**Comment by ericmandel** [comment]
This is fixed and updated in GitHub. Thanks for pointing it out.
