### ISSUE TITLE
'JS9.Load()' cannot load FITS file properly but 'File -> open local file' can

### ISSUE THREAD

**Issue by cylammarco** [ericmandel/js9#55]
Hi, I am trying to include the `js9-allinone.js` inside an electron application and have encountered a weird behaviour when loading FITS files. If I load a FITS file by using `File -> open local file`, the FITS file can be loaded without any problem. However, if I load the same FITS file with JS9.Load() with an html onclick function, the file cannot be imported properly. I have tried this on [files](http://www.astro.ljmu.ac.uk/~ariclam/tempfile/) with and without extensions, they behave the same. Here are the HTML, JS and warning messages:

HTML:
`
<button type="button" class="btn btn-primary" onclick="javascript:loadFITS()">Load Image</button>
`

JS:
`
    function loadFITS() {
      JS9.Load(__dirname + '/FITS_example/example_isis.fits');
    }
`

Warning messages:

**js9-allinone.js:21135** 
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 FITSIO status = 252: 1st key not SIMPLE or XTENSION**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 6�0�6�3�5�7�7�2�8�6�9�3�*�3�=�6�4�3�0�0�**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
pA @ js9-allinone.js:21153
nB @ js9-allinone.js:21153
mB @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Failed to move to HDU number 3 (ffmahd).**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 6�0�6�3�5�7�7�2�8�6�9�3�*�3�=�6�4�3�0�0�**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
pA @ js9-allinone.js:21153
nB @ js9-allinone.js:21153
mB @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Failed to move to HDU number 3 (ffmahd).**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 6�0�6�3�5�7�7�2�8�6�9�3�*�3�=�6�4�3�0�0�**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
pA @ js9-allinone.js:21153
nB @ js9-allinone.js:21153
mB @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**js9-allinone.js:21135 Failed to move to HDU number 3 (ffmahd).**
put_char @ js9-allinone.js:21135
write @ js9-allinone.js:21135
write @ js9-allinone.js:21135
doWritev @ js9-allinone.js:21135
___syscall146 @ js9-allinone.js:21135
Jz @ js9-allinone.js:21153
lB @ js9-allinone.js:21153
kB @ js9-allinone.js:21153
gf @ js9-allinone.js:21139
pc @ js9-allinone.js:21152
Xb @ js9-allinone.js:21152
ccall @ js9-allinone.js:21135
(anonymous) @ js9-allinone.js:21135
a.Image.mkRawDataFromHDU @ js9-allinone.js:3396
a.Image @ js9-allinone.js:3364
(anonymous) @ js9-allinone.js:3980
Module.getFITSImage @ js9-allinone.js:21169
Module.handleFITSFile.fileReader.onload @ js9-allinone.js:21169
load (async)
Module.handleFITSFile @ js9-allinone.js:21169
a.handleFITSFile @ js9-allinone.js:3779
(anonymous) @ js9-allinone.js:3960
g.onload @ js9-allinone.js:3774
load (async)
a.fetchURL @ js9-allinone.js:3774
(anonymous) @ js9-allinone.js:3963
loadFITS @ index.html:192
onclick @ index.html:123

**Comment by ericmandel** [comment]
Hmmm ... I've never tried to do this, but it seems to work using a slighty modified version of js9allinone.html (see below).

Where is __dirname defined in your setup? I had to define it explicitly in the web page this way, since there is no access to the node __dirname on the web page:
````
    <script>
    var __dirname = ".";
    function loadFITS(){ JS9.Load(__dirname + '/fits/casa.fits'); }
    </script>
````
Also, is your button on the web page itself, like the test below? Or are you doing something more sophisiticated?

Finally, is there a reason for using the allinone file? When using the full set of js9 files, you basically have a drop-in replacement for ds9. I imagine there are restrictions with the allinone file ... but again, I never thought of using it  in electron until today!

<img width="646" alt="screen shot 2019-02-20 at 8 11 46 am" src="https://user-images.githubusercontent.com/3028875/53094112-428ae780-34e7-11e9-9d4f-b846a7fb65fe.png">

**Comment by ericmandel** [comment]
Grasping at straws a bit, you can try turning off the helper in electron and see if that does anything:
````
js9 -a --doHelper false --webpage ~/js9/debug2.html
````

**Comment by cylammarco** [comment]
(forgot to include the screenshots)

loading with menubar:
<img width="1437" alt="screenshot 2019-02-20 at 14 06 12" src="https://user-images.githubusercontent.com/2545839/53097230-e0e37100-3518-11e9-8785-94e187e6dce7.png">

with JS9.Load():
<img width="1438" alt="screenshot 2019-02-20 at 14 05 27" src="https://user-images.githubusercontent.com/2545839/53097237-e476f800-3518-11e9-9a82-22757e0dd3fd.png">

> Where is __dirname defined in your setup? I had to define it explicitly in the web page this way, since there is no access to the node __dirname on the web page:
> 
> ```
>     <script>
>     var __dirname = ".";
>     function loadFITS(){ JS9.Load(__dirname + '/fits/casa.fits'); }
>     </script>
> ```

My `__dirname` is basically the same as your `.`

> Also, is your button on the web page itself, like the test below? Or are you doing something more sophisiticated?
> 

It's like yours, the only difference is I used the bootstrap <button> instead of <a>

> Finally, is there a reason for using the allinone file? When using the full set of js9 files, you basically have a drop-in replacement for ds9. I imagine there are restrictions with the allinone file ... but again, I never thought of using it in electron until today!

When I use the full set of js9 files with

```
  <script type="text/javascript" src="../node_modules/js9/js9prefs.js"></script>
  <script type="text/javascript" src="../node_modules/js9/js9support.min.js"></script>
  <script type="text/javascript" src="../node_modules/js9/js9.min.js"></script>
  <script type="text/javascript" src="../node_modules/js9/js9plugins.js"></script>
  <script type="text/javascript" src="../node_modules/js9/js9usermenus.js"></script>
```

I can't even load a FITS file from the menubar, jpg is fine. So it's just like the error message says, 'no FITS module available to process FITS file'. The version of js9 is the most updated one, downloaded into the node_modules with ```npm install https://github.com/ericmandel/js9.git```. The error messages I get are :

```
astroem.js:1 Uncaught SyntaxError: Unexpected identifier
js9worker.js:1 Uncaught SyntaxError: Unexpected identifier
js9.min.js:457 Uncaught Error: no FITS module available to process FITS file
    at Object.a.error (js9.min.js:457)
    at Object.a.handleFITSFile (js9.min.js:449)
    at Object.Load (js9.min.js:630)
    at XMLHttpRequest.g.onload (js9.min.js:444)
a.error @ js9.min.js:457
a.handleFITSFile @ js9.min.js:449
(anonymous) @ js9.min.js:630
g.onload @ js9.min.js:444
load (async)
a.fetchURL @ js9.min.js:444
(anonymous) @ js9.min.js:633
loadFITS @ index.html:198
onclick @ index.html:129
```
<img width="1441" alt="screenshot 2019-02-20 at 14 08 28" src="https://user-images.githubusercontent.com/2545839/53097324-1c7e3b00-3519-11e9-932c-cf00ff529354.png">

**Comment by cylammarco** [comment]
To clearify a little bit more, I am using electron-forge to build the project.

when I compile them into standalone application with the js9-allinone (top) and the full set of js9 (bottom), I get these instead:
<img width="1440" alt="screenshot 2019-02-20 at 14 39 10" src="https://user-images.githubusercontent.com/2545839/53099433-ab8d5200-351d-11e9-89ab-5203de031117.png">
<img width="1438" alt="screenshot 2019-02-20 at 14 39 49" src="https://user-images.githubusercontent.com/2545839/53099435-ab8d5200-351d-11e9-8308-9a34a3d475f8.png">

If you happen to be using Mac, you should be able to examine [this](http://www.astro.ljmu.ac.uk/~ariclam/tempfile/ASPIRED-fullds9.zip
), double clicking the file after unzipping should bring you to that page.

**Comment by ericmandel** [comment]
This is the key message:
````
js9.min.js:457 Uncaught Error: no FITS module available to process FITS file
````
You need these files to be available:
````
-rw-r--r--@  1 eric  staff  2889439 Feb 13 10:10 astroem.js
-rw-r--r--@  1 eric  staff   154813 Feb 13 10:10 astroemw.js
-rw-r--r--@  1 eric  staff  1513757 Feb 13 10:10 astroemw.wasm
````
even when using js9-allinone.js. There is an asynchronous action during JS9.init() that loads either the asmjs-based astroem.js or the two wasm-based files at startup, depending on the capabilities of the browser. Those files contain the FITS-handling code, so my guess is that you are not picking up the files properly.

**Comment by ericmandel** [comment]
OK, I have your app downloaded and I am getting the "no FITS module available" error. I also see you have the requisite files available. So let me have a look into this ...

**Comment by ericmandel** [comment]
After opening ASPIRED, I see this error message:

<img width="1230" alt="screen shot 2019-02-20 at 11 12 56 am" src="https://user-images.githubusercontent.com/3028875/53106230-98b85480-3500-11e9-86f7-56a33d37c518.png">

There are two issues involved:

1. The above-mentioned astroem.js file needs to be in the Resources/app/src directory (its currently in the Resources/app/node_modules/js9/ directory containing all of the js9 source)

2. I guess it needs to be pre-compiled into your system.

**Comment by ericmandel** [comment]
I'm no longer sure why the JS9 init is looking for the astroem.js file in Resources/app/src, since it's loading js9.min.js from the node_modules directory. I'll continue playing one my end, but hopefully the above hints will give you some ideas. We've got to get the astroem.js file loaded properly.

**Comment by ericmandel** [comment]
BTW, your init also needs to find the file:
````
jsworker.js
````
as described in https://js9.si.edu/js9/help/webpage.html:
````
During startup, JS9 will asynchronously load the js9worker.js file in order to create a worker process.
It also will load either the astroem.js file or the astroemw.js and astroemw.wasm files, depending on 
whether WebAssembly is supported on your browser.
````
So I think we only need to figure out how to get your system to find and load these files. 

Note that you mght end up wanting to turn of wasm support, if you have problems loading the astroemw.wasm file (a binary web assembly file). You can do this by setting the globalOpts variable useWasm to false in js9prefs.js.

**Comment by cylammarco** [comment]
Please see if any of these are helpful:

I think this is related to how electron-compile pack the dependencies, if I explicitly include `<script type="text/javascript" src="../node_modules/js9/astroem.js"></script>`, that `astroem.js` not found error message disappears and a new one comes up when loading FITS file, it is related to `handleFITSFile`.

  | abort | @ | js9-allinone.js:21169
-- | -- | -- | --
  | ZD | @ | js9-allinone.js:21162
  | EA | @ | js9-allinone.js:21153
  | rf | @ | js9-allinone.js:21139
  | Ae | @ | js9-allinone.js:21139
  | Ee | @ | js9-allinone.js:21139
  | Xe | @ | js9-allinone.js:21139
  | bc | @ | js9-allinone.js:21152
  | ccall | @ | js9-allinone.js:21135
  | Module.handleFITSFile.fileReader.onload | @ | js9-allinone.js:21169
  | load (async) |   |  
  | Module.handleFITSFile | @ | js9-allinone.js:21169
  | a.handleFITSFile | @ | js9-allinone.js:3779
  | (anonymous) | @ | js9-allinone.js:3960
  | (anonymous) | @ | js9-allinone.js:3567
  | dispatch | @ | js9-allinone.js:20
  | q.handle | @ | js9-allinone.js:20

With the `astroem.js` loaded, if I type `JS9.Load(some-file-name.fits)` in the Console, the previous error "no FITS module available" still appears.

How is the loading of FITS file different between the using of the usermenu button and scripting with JS9.Load()?

**Comment by ericmandel** [comment]
The menu's Open passes a File blob directly to the fits handler, while JS9.Load() has performs an XHR retrieve first, which returns a blob, which them gets processed. I am unable to reproduce your success with the menu's Open command, I only get "no FITS module available", which I believe is the correct error.

I can put the files in a location that gets found but then I get the error "but it was not precompiled". That must be an electron-compile error. Do you know how to fix that?

**Comment by ericmandel** [comment]
I see the problem: JS9 is not figuring out the install directory (where the JS9 files are located). It therefore tries to load astroem.js from the wrong place.

You can explicitly set the install directory location in your js9prefs.js file. Here is what you need to add:
````
                "installDir":       "../node_modules/js9",                     
````
Thus, my edited js9prefs.js file from your node_modules/js9 directory looks like this:
````
var JS9Prefs = {                                                                
  "globalOpts": {"helperType":       "none",                                    
                 "helperPort":       2718,                                      
                 "helperCGI":        "./cgi-bin/js9/js9Helper.cgi",             
                 "fits2png":         false,                                     
                 "debug":            0,                                         
                 "loadProxy":        true,                                      
                 "workDir":          "./tmp",                                   
                 "workDirQuota":     100,                                       
                 "dataPath":         "$HOME/Desktop:$HOME/data",                
                 "analysisPlugins":  "./analysis-plugins",                      
                 "analysisWrappers": "./analysis-wrappers"},
                 "installDir":       "../node_modules/js9",
  "imageOpts":  {"colormap":         "grey",                                    
                 "scale":            "linear"},                                 
}                                                                               

````
Unfortunately, when I change the js9prefs.js file in the node_modules/js9 directory, it does not seem to get loaded, as if the old file is cached. Can you tell me how to fix that? Or can you just add the installDir property to your js9prefs.js and try again?

**Comment by ericmandel** [comment]
One other problem: you are loading js9-allinone.css, even when you are not loading js9-allinone.js. That is why the install directory cannot be found. For the present, I strongly recommend that you not load the allinone css and js files and, in fact, load the unminified js9.js so that we can see the error stack more clearly.

**Comment by cylammarco** [comment]
> Unfortunately, when I change the js9prefs.js file in the node_modules/js9 directory, it does not seem to get loaded, as if the old file is cached. Can you tell me how to fix that? Or can you just add the installDir property to your js9prefs.js and try again?

I tried half a day and I can't get the application to read from the modified file instead of the "cache". I'll keep looking/trying.

> I am unable to reproduce your success with the menu's Open command, I only get "no FITS module available", which I believe is the correct error.

I just realised that launching the application with and without (dev) having it packaged give different results... From here on I will only refer to the problems from a compiled electron application.

I have added the install path, and changed all the `min` to full size files, it still gets stuck at the handling a new FITS file:

  | JS9.error | @ | js9.js:17284
-- | -- | -- | --
  | Module.error | @ | astroem.js:38
  | Module.errchk | @ | astroem.js:38
  | Module.handleFITSFile.fileReader.onload | @ | astroem.js:38
  | load (async) |   |  
  | Module.handleFITSFile | @ | astroem.js:38
  | JS9.handleFITSFile | @ | js9.js:16917
  | (anonymous) | @ | js9.js:20416
  | xhr.onload | @ | js9.js:16809
  | load (async) |   |  
  | JS9.fetchURL | @ | js9.js:16788
  | (anonymous) | @ | js9.js:20514
  | loadFITS | @ | index.html:201
  | onclick | @ | index.html:132

This file should be able to replicate the result I mentioned.
http://www.astro.ljmu.ac.uk/~ariclam/tempfile/ASPIRED.zip

**Comment by ericmandel** [comment]
We are close: you are now loading the FITS support code correctly, so that you can drag/drop a FITS file onto the display:

<img width="703" alt="screen shot 2019-02-22 at 7 03 35 am" src="https://user-images.githubusercontent.com/3028875/53241604-2bc3cc80-3670-11e9-81f0-fe09f653312b.png">

The error message is now coming directly from the CFITSIO library.

My first guess is that the problem now is in specifying the path of the file you are trying to load. The path has to be relative to the web page. But I'm away right now ... will be able to say more when I return on Monday ...

**Comment by ericmandel** [comment]
Attached is a screenshot of some debugging information regarding the version of ASPIRED you sent me last week:

1. the astroemURL is set to astroem.js, which is the asm version of the cfitsion support
2. the fact that JS9.fits is a non-empty object tells us that the FITS support was loaded successfully
3. but trying to load your example_isis.fits file gives the CFITSIO error: "error reading from FITS file"
4. the Astroem.vcat() call prints out the first 2880 bytes of the in-memory FITS file, which was created by retrieving your file as a blob using an XHR call, and then using the FileReader API to convert this blob back to binary data for in-memorystorage and processing. What we see is that the "FITS file" contents is an error message about "failure to compile" instead of containing the FITS bits.

I think this error is involved with how your platform deals with XHR calls: it seems that the platform is giving the "failure to compile" error when an XHR call is made. Can that be fixed?

<img width="1237" alt="screen shot 2019-02-24 at 5 51 33 pm" src="https://user-images.githubusercontent.com/3028875/53306589-0c3dc700-385d-11e9-94bb-2daef256e77f.png">

**Comment by ericmandel** [comment]
I haven't looked into electron-compile much, but you probably want something like this for FITS files:

<img width="784" alt="screen shot 2019-02-24 at 7 44 42 pm" src="https://user-images.githubusercontent.com/3028875/53308137-c4bf3700-386c-11e9-8aff-60f73b021692.png">

**Comment by cylammarco** [comment]
I am unable to find a way not to compile some files with electron-forge (which uses electron-compile at some stage for this current distribution). 

I think it is indeed related to XHR calls to some "compiled FITS files" because typing this in the console works:

JS9.Load('https://js9.si.edu/js9/fits/casa.fits.gz')

**Comment by ericmandel** [comment]
Are you saying that you created a .compilerc file as shown above and in this electron-compile doc:
https://github.com/electron-userland/electron-compile#how-can-i-compile-only-some-file-types-but-not-others
but that it was ignored by electron-forge? If that is the case, I would open an issue on the electron-forge Github site. 

I see this issue:
https://github.com/electron-userland/electron-forge/issues/692
which seems similar to the current problem, and the answer seems to point back to specifying passthrough in .compilerc, but I've never used this platform ...

**Comment by cylammarco** [comment]
I think it's my lack of understanding of how to use .compilerc file at the moment. I will reply with more details once I have figured it out.

I believe the remaining problems are electron's fs read/write related, not with the JS9. Thank you very much for your help!

**Comment by ericmandel** [comment]
Yeah, it's a little unclear where .compilerc should be located. Given that it's needed at runtime, I would guess that it has to be in the Electron tree somewhere ... but the docs are unclear to me ...

Let me know how I can help.
