### ISSUE TITLE
Does Pyodide (access to Python scientific stack from JS) open up any avenues?

### ISSUE THREAD

**Issue by DougBurke** [ericmandel/js9#56]
https://alpha.iodide.io/ is another place where JS9 could appear. 

https://github.com/iodide-project/pyodide is related to this but may be useful from within JS9 itself.

**Comment by ericmandel** [comment]
iodide: yeah, it looks good, and I replied to a recent tweet of theirs ... no response.

pyodide: wouldn't it be cool to run python scripting in the browser, communicating with js9 ... could be an interesting collaborative project ... although on-the-fly loading/merging of wasm files is not there yet, AFAIK. Some day we'll be able to load the wasm modules we want on the fly and make the browser just into another OS ...
