### ISSUE TITLE
Cannot use the desktop app on macOS with recent versions of Electron

### ISSUE THREAD

**Issue by jzuhone** [ericmandel/js9#59]
Current versions of Electron do not install it on macOS in either of the paths `/Applications/Electron.app` or `${HOME}/Applications/Electron.app`, but these are the only paths that the `mkjs9` script appears to recognize.

**Comment by ericmandel** [comment]
How are you installing? I recently installed 5.0.2 from https://github.com/electron/electron/releases/tag/v5.0.2 without a problem, specifically by downloading this link: https://github.com/electron/electron/releases/download/v5.0.2/electron-v5.0.2-linux-x64.zip

If you are using a different install procedure and the result is installing elsewhere, let me know where and I'll add it to the script ...

<img width="565" alt="Screen Shot 2019-06-02 at 5 58 46 PM" src="https://user-images.githubusercontent.com/3028875/58767909-1cea9100-8560-11e9-8c4e-52bd761adaf9.png">

**Comment by jzuhone** [comment]
If you install via `npm` it puts it here: `/usr/local/lib/node_modules/electron/dist/Electron.app/
Contents`

This probably assumes that `npm` in installed under `/usr/local/`. Is there a way to detect electron without having to assume specific paths?

**Comment by ericmandel** [comment]
You can set the environment variable JS9_ELECTRON_APP to:
````
/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
````
and the script should be happy.

> Is there a way to detect electron without having to assume specific paths?

Not that I know of ... you're essentially looking for a random file on disk ... I'll look around again, but in the end, I probably end up adding the standard npm directory to the list.

**Comment by ericmandel** [comment]
OK, I added the npm install location mentioned above to the list checked by Macs, so you should be all set.
