### ISSUE TITLE
JS9 ERROR: image too large for zscale

### ISSUE THREAD

**Issue by briehanlombaard** [ericmandel/js9#6]
Hi Eric,

Another issue I ran into while upgrading from v1.1 to v1.5 is that I get this error when using the "set limits to zscale" in the scaling menu even on very tiny images (1x1 for example). It's possible that I'm doing something wrong but maybe this is a bug?

Let me know if you need any more info from my side.

**Comment by ericmandel** [comment]
This is too weird: the emscripten Module object (some of whose methods are accessed in zscale) is no longer available to the JS9 code. And now I don't see why it ever should have been available, so zscale should never had worked as implemented. Give me a few days to unravel this curious situation -- there's no problem with the algorithm, only with my understanding of emscripten.

**Comment by ericmandel** [comment]
Well ... I still don't know why zscale ever worked, because some needed emscripten methods were not properly exposed to JS9. They are now, and the fix is pushed to GitHub, if you want to try it out.

**Comment by briehanlombaard** [comment]
Thanks for looking into this Eric.

I've tried with the updated code, but I'm still running into some issues. The problem seems to be the fact that I'm including fitsy.js.

When I include it the min and max values are always set to zero. When I remove it the scaling works fine on some test images that I'm using, but then it doesn't seem to be able to render the images I send across a web socket. I get this error: "ERROR from cfitsio.js: datatype conversion overflow".

**Comment by ericmandel** [comment]
zscale: when I include fitsy.js, I see non-zero min and max values both before and after zscale. Can you send me an FITS file that does not work? I'm loading these js files in my debug web page:

````
  <script type="text/javascript" src="js9support.min.js"></script>
  <script type="text/javascript" src="fitsy.js"></script>
  <script type="text/javascript" src="js9.js"></script>
  <script type="text/javascript" src="js9plugins.js"></script>
````

render: I'll look into this using the files I have at hand, but I might need one of your files for this problem as well.

**Comment by ericmandel** [comment]
Thanks to your test file, I found a bug in the JS9 wrapper around cfitsio: it was choosing the wrong data type for the image array when handling bscale/bzero data. This is now fixed and has been uploaded into GitHub.  It's been tested with RefreshImage(), drag&drop, and URL load. You can see the fix by going to http://js9.si.edu and dropping your test file onto the display. (You might have to shift-reload to get the updated support.)

**Comment by ericmandel** [comment]
We still have to deal with zscale, but since it works on my data sets, I'll wait for you to check things out with the above new code.

**Comment by ericmandel** [comment]
> "ERROR from cfitsio.js: datatype conversion overflow".

Fixed by fixing a CFITSIO memory leak.
