### ISSUE TITLE
Error: Task requires configuration of a temporary work directory

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#64]
Hi Eric,

I'm playing around with js9, and trying to get server side analysis working. I have installed js9 in an ubuntu ec2 instance with the following script (run as root): 
```
./configure --with-webdir=/var/www/js9 \
            --with-cfitsio=/soft/saord \
	    --with-helper=nodejs \
	    --prefix=/soft/saord \
	    CC=gcc $*
make
make install
make clean
```
My js9prefs.js file (identical to js9Prefs.json) contains the following: 
```
var JS9Prefs = {
  "globalOpts": {"helperType":	     "nodejs",
  		 "helperPort":       2718, 
		 "helperCGI":        "./cgi-bin/js9/js9Helper.cgi",
		 "fits2png":         false,
		 "debug":	     0,
		 "loadProxy":	     true,
		 "workDir":	     "./tmp",
		 "workDirQuota":     10000,
		 "dataPath":	     "$HOME/Desktop:$HOME/data",
		 "analysisPlugins":  "./analysis-plugins",
		 "analysisWrappers": "./analysis-wrappers",
	         "requireHelper":    true,

  },
  "imageOpts":  {"colormap":	     "grey",
  		 "scale":     	     "asinh"}
}
```
From the directory /var/www/js9, I can start the node helper with 
`node js9Helper.js 1>~/logs/js9node.log 2>&1 &`. 

Then I moved the index.html file from /var/www/js9 into the parent directory /var/www. The apache2 document root is set to /var/www/, so navigating to the server's address in chrome presents the same view as seen at https://js9.si.edu. 

With CORS enabled, I'm able to paste a link to a fits file stored in aws s3 and open it in the browser window, and browser-based analysis tasks work as expected.

However choosing analysis -> upload FITS to make tasks available in the menu produces an alert saying "ERROR: Task requires configuration of a temporary work directory". From js9.si.edu, I'm able to upload with no issue. 

The log from the node helper contains:
```
helper: 0.0.0.0 2718  [10/11/2019, 23:09:09]
...
connect: xxx.xx.xxx.xx (JS9)  [10/11/2019, 23:09:12]
exec: /var/www/js9/analysis-wrappers/js9Xeq [quotacheck]  [10/11/2019, 23:09:33]
```

I've done a fair bit of digging but can't understand the cause of the problem. Do you have any ideas?

Thanks for looking into this!

**Comment by ericmandel** [comment]
Hi Tim,

Sorry, sounds like the documentation is not clear enough ... I'll have a look later ...

Tasks such as uploading a FITS file and LoadProxy require a temp directory to exist -- this is the directory into which the FITS file will be loaded or retrieved. In your prefs file, it's specified as ./tmp:
````
workDir":	     "./tmp",
````
So, given that configuration, all you need to do is:
````
mkdir tmp
````
in /var/www/js9 and restart the helper.

But let me know if you have problems ...

**Comment by timbeccue** [comment]
This is very helpful, thanks!

Uploading the image now works when I run the node helper with root privileges. When I run it normally, I get the error `ERROR: can't create page workDir: EACCESS: permission denied, mkdir '/var/www/js9/tmp/db58833a-143a-4215-8503-608ea846855e'`, which could have been my original problem too (unable to automatically create the tmp directory). 

Could this be related to the way I installed js9 (running the make install commands as root, due to similar permission errors when run normally), or is it more likely something to do with my environment that I need to figure out?

**Comment by ericmandel** [comment]
I'm pretty sure this is all just ordinary Linux permission problems ... I presume /var/www is owned by root? If so, and if it oughtn't to be changed to be owned by you, perhaps you can manually mkdir /var/www/js9 as root and then chown it to yourself before actually installing, so that everything inside js9 is owned by you. That's almost certainly what you want ...

**Comment by timbeccue** [comment]
That seems like it should do the trick. Thanks for the pointers!
