### ISSUE TITLE
Issues with regions (fabric.js?)

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#66]
Hi Eric,

I've recently been getting an error whenever trying to add a region to an image. The browser console shows: 
```
js9.js:13148 
Uncaught TypeError: s.rescaleBorder is not a function
    at JS9.Image.JS9.Fabric.addShapes (js9.js:13148)
    at js9plugins.js:7989
    at Array.forEach (<anonymous>)
    at jQuery.fn.init.callback (js9plugins.js:7891)
    at HTMLLIElement.itemClick (js9support.js:27304)
    at HTMLDocument.dispatch (js9support.js:5222)
    at HTMLDocument.elemData.handle (js9support.js:5030)
```
I'm guessing the line `JS9.Image.JS9.Fabric.addShapes` might be indicative of the problem? Is this something you've seen before?

In case it helps, I've been having other issues recently that seem to stem from the libraries included in js9support. For example, I would get `$.contextMenu is not defined` or something like that, and I've seen others. But I was unable to reproduce these issues just now...

**Comment by timbeccue** [comment]
I should add this this issue is only present in the instance I create in my Vue app. The index.html and other html demos work just fine. But maybe you have a clue as to what part of my configuration might be causing these problems.

**Comment by ericmandel** [comment]
Oh right, that would do it ... I add the rescaleBorder() to Fabric, so if you load a clean copy, its likely to be erased ...

**Comment by ericmandel** [comment]
> I would get $.contextMenu is not defined or something like that, and I've seen others. 

Probably need to be careful about reloading stuff in general?? Context menu is defined in js9support.js.
