### ISSUE TITLE
funcnts2flot: command not found

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#67]
Hi Eric,

I'm getting this error (`funcnts2flot: command not found`) when trying to run the server-side radial profile task. If I ssh into the server and run `funcnts2flot` directly, I get the same error. 

In the logs from the `make` command, I do see 
```
Installing funhist2flot
Installing funcnts2flot
```
and there are no errors following. 

I also found the lines 
```
checking for funtools... no
checking for cfitsio... yes (/the/path)
```

Funtools was installed via `sudo apt install funtools -y`, do you think this is causing the problem? Do I need to specify the installation path when I run the js9 ./configure?

Thanks for your help.

**Comment by ericmandel** [comment]
Just normal path problems: the JS9 *nix bash scripts, including funcnts2flot, get installed in the directory pointed to by the --prefix= switch on JS9 configure (as usual), so you can check your JS9 Makefile to see where they ended up. The JS9 helper has to have that directory in its path when it starts up.

**Comment by ericmandel** [comment]
Hmmm ... to be clear: funcnts and the JS9 bash scripts need to be in the machine where the helper is running ...

**Comment by timbeccue** [comment]
Adding the --prefix directory to PATH before starting the node helper did the trick. Thanks!
