### ISSUE TITLE
Crosshair change event

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#68]
Is it possible to run a function every time the crosshair position changes? I'm trying to implement something like the horizontal/vertical graph in DS9 which show x/y profiles at the crosshair position.

**Comment by ericmandel** [comment]
At the moment, you can simply add a plugin callback looking for mousemove and, in that callback, check to see whether the crosshair is enabled and the shift key is down, something like:
````
function docut(im, ipos, evt){
    if( im && im.crosshair && im.params.crosshair && evt.shiftKey ){
        console.log("call the update: %s %s", ipos.x, ipos.y);
    }
}

JS9.RegisterPlugin("MyPlugins", "CrosshairCut",
		   function(){},
		   {onmousemove: docut, winDims: [0, 0]});

````

If you are uncomfortable looking into the image object,  I can easily add a more official oncrosshairdisplay option as input to a plugin ...  I just have to get to a stable place to update it ...

**Comment by timbeccue** [comment]
This is perfect, thanks!
