### ISSUE TITLE
Javascript API 

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#71]
Hi Eric,

I'm wondering if there is a general method (or source I could reference) for executing tasks listed in the menu with javascript. It looks like a lot of them are available and documented in the JS9 public API page and elsewhere, but not all. 

For example, I recently discovered the '(menu) View -> Keyboard Actions' plugin, with a clickable button accompanying each keyboard action. I was trying to programmatically toggle the crosshairs, and this plugin contained a button that did exactly what I wanted. But I couldn't trace down the onclick javascript to add the functionality in my own button.

Are there existing JS9 functions for clickable menu items (perhaps I missed them in the docs, or they haven't been added yet), or would it require significant re-architecting to use?

**Comment by ericmandel** [comment]
The keyboard actions support is implemented in two levels:

JS9.globalOpts.keyboardActions is an array of keyboard actions mapped to specific keys. Consider the 0 key, which resets the zoom, as shown in the Keyboard Action plugin:

<img width="432" alt="Screen Shot 2019-11-20 at 7 41 13 PM" src="https://user-images.githubusercontent.com/3028875/69290374-c0426780-0bcd-11ea-9b52-9366c9243fe5.png">

In the JS9.globalOpts.keyboardActions object there is a property called "0" whose value is ""reset zoom":

<img width="264" alt="Screen Shot 2019-11-20 at 7 43 34 PM" src="https://user-images.githubusercontent.com/3028875/69290531-43fc5400-0bce-11ea-919a-4513e9702566.png">

And "reset zoom" is a property of the JS9.Keyboard.Actions object which actually defines the function:

<img width="255" alt="Screen Shot 2019-11-20 at 7 46 23 PM" src="https://user-images.githubusercontent.com/3028875/69290611-7ad26a00-0bce-11ea-8d0d-128004175821.png">

I believe the args  to keyboard action functions are always:
````
 JS9.Keyboard.Actions["name of the action"](im, ipos, evt)
````
where ipos is the image position of the mouse, evt is the event triggering the call, both often can be omitted if the call does not warrant a mouse position etc.

What this does is allow us to define a lot of actions and only map some of them to specific keys. But of course you can call any of these directly. e.g.:
````
im = JS9.GetImage({display: "myJS9"});
JS9.Keyboard.Actions["reset zoom"](im)
````
will reset the zoom on the "myJS9" display (obviously zoom does not need the ipos or evt args). Or you can add these calls to your own GUI stuff ...

The current keyboard actions are defined in plugins/core/keyboard.js. But NB: you can define your own keyboard actions and modify Js9.globalOpts.keyboardActions to assign a key to them and then add them to your own GUI.

Believe it or not, this is documented in the Keyboard Actions plugin in the Help->JS9Plugins->Keyboard Actions menu option. But now its documented here too, which is good. Let me know if you need more info ...

**Comment by timbeccue** [comment]
Ah, very helpful! Both the specific instruction, and the reminder about the plugin docs in the help menu. This makes things quite a bit easier. Thanks!
