### ISSUE TITLE
JS9.Load("file", {ra: 0, dec: 0}) doesn't pan

### ISSUE THREAD

**Issue by hombit** [ericmandel/js9#73]
I tried this example from [the public API page](https://js9.si.edu/js9/help/publicapi.html#load) with different `ra` and `dec` values:
```js
JS9.Load("fits/casa.fits", {ra: 350.866689, dec: 58.811671)};
```
(Note a brackets typo here)

It loads the image but doesn't pan it. I tried it on my own installation of release 3.0 and on https://js9.si.edu via console. I use Safari 13.1 and Firefox 68.0

**Comment by ericmandel** [comment]
Thanks for the typo! The panning support was added after the release of 3.0, so you can get it if you clone the current repository. Alternatively, you can use the onload  callback to accomplish the same thing:
````
JS9.Load("fits/casa.fits", {onload: function(im) {
    JS9.SetPan({ra: 350.866689, dec: 58.811671}, {display: im});
}});
````

**Comment by ericmandel** [comment]
P.S. The main web site does pan when I do this:
````
JS9.Load("js9/data/fits/casa.fits", {ra: 350.866689, dec: 58.811671})
````
However, if you already have casa.fits loaded,and call JS9.Load() again, it will not reload the file but just redisplay it, and I think in this case it does not pan. Is that what you are seeing?

**Comment by hombit** [comment]
Thank you!

>  Is that what you are seeing?

Yes, I think so
