### ISSUE TITLE
JS9 ERROR: cannot load: ../astroemw.wasm ... please check the url/pathname

### ISSUE THREAD

**Issue by LeoBaro** [ericmandel/js9#77]
I've been following [the installation docs](https://js9.si.edu/js9/help/install.html), paragraph "Run JS9 using the file:// URI". 
The docs assert:

> After the source code is retrieved, you should be able to load any of the js9*.html web pages into your browser using the file:// URI. For example, if you unpacked the tar file into /Users/me on a Mac, then you can point your browser to:
    file:///Users/me/js9-[version]/js9basics.html
to see the basic JS9 demo page. 

When I open js9basics.html with Firefox (on Ubuntu19.10) the following error message appears:

> JS9 ERROR: cannot load: ../astroemw.wasm ... please check the url/pathname

What I am missing? Thank you

**Comment by ericmandel** [comment]
@LeoBaro I haven't seen this error in Firefox, but its possible that Firefox is now also throwing CORS errors when using the file:// URI. You can check this by looking at the Javascript console output. The inability to load astroemw.wasm does indicate a CORS problem. And if you you can just bypass this whole issue by starting up a python web server in the js9 directory:
````
python3 -u -m http.server 8080
````
and then loading web pages in that directory from localhost:8080

Please let me know if Ubuntu Firefox is  indeed throwing CORS errors, that would be new ...
