### ISSUE TITLE
JS9.ChangeRegions() to change position incorrect after zooming image

### ISSUE THREAD

**Issue by AstroAndyN** [ericmandel/js9#81]
Hi.
I'm developing a wrapper using the JS9 Public API for school children (simplified interface, easy to translate etc).

I've just discovered that calling `JS9.ChangeRegions(region, {x: xval, y: yval});` immediately after any `JS9.SetZoom(...)` causes the position of the region to change dramatically, not to (xval,yval) (usually off the image). It does not do this if the region is moved "by hand" before calling `ChangeRegions()`.

After a bit of hunting, I discovered that adding a `SelectShapes()` call near to the beginning of `JS9.Fabric.changeShapes` in js9.js solved the problem, though I'm not sure why.

E.g. this fixes the problem:
```
JS9.Fabric.changeShapes = function(layerName, shape, opts){
    let i, s, sobj, bopts, layer, canvas, ao, rlen, maxr, zoom, exports;
    let topts, xopts;
    const orad = [], cpts = [];
    layer = this.getShapeLayer(layerName);
    // sanity check
    if( !layer || !opts ){ return; }
    // opts can be an object or json
    if( typeof opts === "string" ){
        try{ opts = JSON.parse(opts); }
        catch(e){ JS9.error(`can't parse shape opts: ${opts}`, e); }
    }
    // delay changing the region, if this image is not the one being displayed
    if( this.display.image !== this ){
        this.delayedShapes = this.delayedShapes || [];
        this.delayedShapes.push({layer: layerName, shape: shape,
                                 mode: "change", opts: opts});
        return;
    }
    // AMN BUGFIX: 27/01/22: This is required if ChangeRegions()/ChangeShapes() is called after zooming in or out
    JS9.SelectShapes(layerName, shape);
    // AMN ENDBUGFIX
    canvas = layer.canvas;

```
Any thoughts?
Many thanks (and thank you for JS9 - it is making my life dramatically easier!)
Andy

**Comment by ericmandel** [comment]
I'm having some trouble reproducing this, which doesn't mean there isn't a bug. Simple tests all seems to work, as does zooming in/out using the < and > keys and then calling ChangeRegions:

<img width="383" alt="Screen Shot 2022-01-27 at 3 52 04 PM" src="https://user-images.githubusercontent.com/3028875/151442021-66496d66-c1df-4e54-9263-b285f142782c.png">

So I'm missing something ... can I get a copy of the FITS file you are using (since this problem might be FITS wcs-dependent) as well as the position changes you are making? I just need to reproduce it and we can get it fixed.

**Comment by ericmandel** [comment]
Wait, wait, I made it happen once .... let me continue, I should have enough to go one ...

**Comment by ericmandel** [comment]
My experiments indicate that this happens only when the region being moved is selected. There is some special code in ChangeRegions() that deals with selected regions. It was valid for Fabric.js 3.x, but perhaps is no longer valid for Fabric.js 4.x (as does happen). I'll look into this. Nice bug, thanks!

**Comment by ericmandel** [comment]
OK,  this should be fixed. New code is updated in GitHub. There actually was a common problem in Set{Pan,Zoom,Flip}: after doing these operations, it's unclear how to update the selection completely,  so your inspired suggestion to fully regenerate the selection was what I eventually used (though in another part of the JS9 code). If it works for you too, feel free to close this issue.

**Comment by AstroAndyN** [comment]
Yes, that's fixed it - thanks very much!
