### ISSUE TITLE
Dynamic resizing of existing JS9 displays

### ISSUE THREAD

**Issue by michaelwille** [ericmandel/js9#9]
Hi Eric,

I would like to request a new public API function, e.g. JS9.SetSize(width, height), which allows the user to change the size of an already existing JS9 display dynamically. If there are multiple displays and hence multiple divs, the display in question could, e.g., be specified via the {display: [div_id]} object, similar to other functions of the public API.

I came across this problem when i tried to embed a JS9 display into an extJS container whose size adapts to the size of the browser window. In this case it would be favorable to have the JS9 display (i.e. the menubar and the image) use all available space in the container (which is essentially a div) automatically, which makes resizing necessary.

Cheers,
Michael

**Comment by ericmandel** [comment]
Hi Michael,

This is a really good idea and I will work on it in December. I hope implementation will basically be a book-keeping problem: changing canvas dimensions on all of the canvases associated with a display (catalogs, regions, main display for all images) and making sure the canvas-based 2D graphics get updated properly.

Which brings up the question: when you change the size of the display, where in the new canvas should the original be embedded? In the center? Or should this depend on how the resize was done, e.g., if you resize from the lower-right corner, then the old canvas might get embedded at the upper left ... if you catch my meaning. I wonder if we will need an extra argument to specify: center, upperLeft, upperRight, lowerLeft, lowerRight, left, right, top, bottom. What would be your expectation? Or even x,y args for more precise placement ... though that gets complicated for the user.

**Comment by michaelwille** [comment]
Hi Eric,

thank you for taking care of this issue so quickly. I could imagine that the book-keeping problem will cause quite some work as there can be many elements in a display.

Right now I don't see a problem if the original always used the upper left of the new canvas as a point of reference, independent of how the resize was performed but maybe there is something I missed.
From what I have seen so far, newly opened images in JS9 are always displayed in the center of a canvas. So if the canvas gets resized, the image should probably be moved to the new center. If any panning had been performed before the resize, it should be re-applied then in order to have the same pixel back in the center as before. The same x/y translation (without the panning correction) should also be applicable to any regions in the image. I don't think that the zoom level should be touched by a canvas resize, even if it was set to "zoom to fit" at that time. At least it would save work and potential rounding errors to not adjust it dynamically.

**Comment by ericmandel** [comment]
Hi Michael,

I have implemented public API support for re-sizing the JS9 display dynamically:
````
  JS9.ResizeDisplay(width, height);
````
Upon reflection, I decided simply to re-center image in the new display, without offering options to place the current display in another location. If there is call for this functionality, it can be added later. And it probably would be really cool if we could add an option to put resize handles on a JS9 display ... also later ... 

I've tested it pretty thoroughly and it all seems to work as expected. But this is the sort of thing that shows a developer's blind spot really well, so I'll leave it to you to tell me if there is a problem. It's uploaded in GitHub.

**Comment by michaelwille** [comment]
Hi Eric,

I just tried it out and it works perfectly so far. Thank you very much for the great (and quick) work!
The only remaining issue I see right now is that the size of the associated JS9 menu does not match the size of the display anymore after a resize. I am not sure how it is "wired" internally, but maybe it would make sense to extend the resize command such that it is also capable of resizing menus? Or is it already possible and I am just missing something?

**Comment by ericmandel** [comment]
Oh right, great idea, which I have implemented. The default is now to resize the width of the menubar, but this can be changed by passing an optional opts object:
````
JS9.ResizeDisplay(500, 400,  {resizeMenubar: false},  {display: "myJS9"})
````
Resizing the menubar should have been possible without this intervention, but apparently I forgot to assign a default id to the menubar div, an oversight which is now fixed.

**Comment by michaelwille** [comment]
Thanks again! I have done some testing and everything works just fine now. The new resize functionality has helped us simplify our code quite a bit which is very nice.
That's all from my side for now, but if you like we can leave the topic open for discussing the resize handles you mentioned earlier. Right now I don't see a specific need for them in our project, but it would definitely be nice to have the option.

**Comment by ericmandel** [comment]
I'm glad resize is working, as it's an important addition. I'm going to close this issue, though. Adding resize handles just means writing a plugin to decorate a given display, which I have put on my TODO list. It's the sort of project one does as a rest from a larger project (unless someone else does it first).
